---
grails:
    profile: web
    codegen:
        defaultPackage: agha.variantstorage
    spring:
        transactionManagement:
            proxies: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none

endpoints:
    jmx:
        unique-names: true

---
# Dataset names and variant set names to be uppercased?
uppercase.names: true

environments:
  development:
    camel.import: "file:/home/philip/ga4gh_registration?move=archived"
    existing.files.root: "/home/philip/ga4gh-server-env/cpi_datasets"
    hla.root: "/home/philip/hla"
    samtools.path: "samtools"
  test:
    grails.serverURL: "https://130.56.244.154/ga4gh_frontend"
    ga4gh_repo.path: "/mnt/ga4gh/ga4gh-server-env/bin"
#    ga4gh_repo.registry: "/mnt/ga4gh/registry.db"
    camel.import: "file:/mnt/u86_nfs/camel?move=archived"
    existing.files.root: "/mnt/u86_nfs/variantdb/runs"
    hla.root: "/mnt/hla-genotyper"
    samtools.path: "/bin/samtools"
  production:
    grails.serverURL: "https://130.56.244.154/variantStorage"
    camel.import: "file:/mnt/u86_nfs/camel?move=archived"
    existing.files.root: "/mnt/u86_nfs/variantdb/runs"
    hla.root: "/mnt/hla-genotyper"
    samtools.path: "/bin/samtools"



# grails mail plugin setting
grails.mail.host: "smtphost.anu.edu.au"
grails.mail.default.from: "APF Informatics <it.apf@anu.edu.au>"

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory


environments:
    development:
        dataSources:
            dataSource:
                driverClassName: "org.postgresql.Driver"
                dbCreate: "update"
                pooled: true
                url: "jdbc:postgresql://localhost:5432/variant_storage"
                username: "postgres"
                password: "postgres"
    test:
        dataSources:
            dataSource:
                driverClassName: "org.postgresql.Driver"
                dbCreate: "update"
                url: "jdbc:postgresql://localhost:5432/ga4gh_frontend"
                username: "agha"
                password: "changeme"


    production:
            dataSource:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                driverClassName: "org.postgresql.Driver"
                dbCreate: "update"
                pooled: true
                url: "jdbc:postgresql://localhost:5432/ga4gh_frontend"
                username: "agha"
                password: "changeme"




